"""
Additional guide entries for The GTM Index.
Imported by build.py. Each function returns word count via _write_guide.
"""

GUIDE_EXTRAS = [
    # Role vs Role
    {"slug": "sdr-vs-bdr-which-role", "title": "SDR vs BDR: How These Two Pipeline Roles Differ",
     "meta": "SDR vs BDR explained. What each role owns, ramp time, pay benchmarks, reporting structure, and which one fits your B2B SaaS pipeline motion in 2026.",
     "summary": "What each role owns, where they overlap, comp benchmarks, and which one fits your pipeline motion.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "inside-sales-vs-field-sales", "title": "Inside Sales vs Field Sales: A 2026 B2B Comparison",
     "meta": "Inside sales vs field sales benchmarks. Quota, comp, ramp, segment fit, and how hybrid motions have changed the math in B2B SaaS and enterprise sales.",
     "summary": "Quota, comp, ramp, and segment fit. How hybrid motions reshaped the inside vs field decision.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "demand-gen-vs-growth-marketing", "title": "Demand Gen vs Growth Marketing: How They Differ",
     "meta": "Demand gen and growth marketing compared. Scope, KPIs, reporting lines, and how to decide which function your B2B SaaS company should hire first.",
     "summary": "Scope, KPIs, and reporting lines. How to decide which function to build first.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "demand-gen-vs-product-marketing", "title": "Demand Gen vs Product Marketing: Scope and Overlap",
     "meta": "Demand gen vs product marketing in B2B SaaS. What each role owns, where the messaging handoff lives, hiring order, and how to avoid stepping on each other.",
     "summary": "What each role owns, where the messaging handoff lives, and which to hire first.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "marketing-ops-vs-revops", "title": "Marketing Ops vs RevOps: Scope, Tools, and Reporting",
     "meta": "Marketing ops vs RevOps in B2B SaaS. Tool stack, reporting lines, comp benchmarks, and when to split MOps off into a standalone function from RevOps.",
     "summary": "Tool stack, reporting lines, comp benchmarks, and when to split MOps off as its own function.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "revops-vs-sales-ops", "title": "RevOps vs Sales Ops: When the Rebrand Matters",
     "meta": "RevOps vs sales ops compared. Scope, reporting lines, the cross-functional shift, and when the rebrand is real versus when it is a cosmetic title change.",
     "summary": "When the RevOps title is a real scope expansion versus a cosmetic rename of sales ops.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "customer-success-vs-account-management", "title": "Customer Success vs Account Management Compared",
     "meta": "Customer success vs account management in B2B SaaS. Scope, comp, ownership of renewals and expansion, and how to staff the post-sale motion correctly.",
     "summary": "Scope, comp, ownership of renewals and expansion, and how to staff the post-sale motion.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "account-manager-vs-account-executive", "title": "Account Manager vs Account Executive: Role Differences",
     "meta": "Account manager vs account executive in B2B SaaS. Quota, comp structure, segment fit, and how the two roles overlap on cross-sell and renewal motions.",
     "summary": "Quota, comp, and where the cross-sell handoff lives between AM and AE roles.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "vp-sales-vs-cro", "title": "VP Sales vs CRO: When to Make the Title Shift",
     "meta": "VP Sales vs CRO compared. Scope, comp, the right ARR window to make the title shift, and the most common board-driven mistakes in the promotion path.",
     "summary": "Scope, comp, and the right ARR window for the VP Sales to CRO title shift.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "solutions-engineer-vs-sales-engineer", "title": "Solutions Engineer vs Sales Engineer: Title Comparison",
     "meta": "Solutions engineer vs sales engineer. Title use, scope by stage, comp benchmarks, and how the SE function specializes at scale in B2B SaaS pre-sales.",
     "summary": "Title use, scope, and comp benchmarks across the SE function in B2B SaaS.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "chief-revenue-officer-vs-chief-sales-officer", "title": "Chief Revenue Officer vs Chief Sales Officer Explained",
     "meta": "Chief revenue officer vs chief sales officer compared. Scope, reporting lines, comp ranges, and the strategic reasons companies pick one title over the other.",
     "summary": "Scope, reporting, comp, and why companies pick CRO over CSO or vice versa.",
     "word_target": 1400, "date": "2026-05-15"},

    # Hiring guides
    {"slug": "how-to-hire-your-first-sdr", "title": "How to Hire Your First SDR: A B2B Founder Guide",
     "meta": "How to hire your first SDR in B2B SaaS. Timing signals, comp targets, scorecard, interview loop, and the most common founder mistakes in the first SDR hire.",
     "summary": "Timing signals, comp targets, scorecard, and interview loop for your first SDR hire.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "how-to-hire-your-first-account-executive", "title": "How to Hire Your First AE: A B2B SaaS Founder Guide",
     "meta": "How to hire your first AE in B2B SaaS. Pre-AE checklist, comp targets, profile by ACV segment, interview loop, and the early-stage AE hiring mistakes to avoid.",
     "summary": "Pre-AE checklist, comp targets, ACV-based profile, and how to run the loop.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "how-to-hire-a-fractional-cro", "title": "How to Hire a Fractional CRO: Scope, Cost, and Fit",
     "meta": "How to hire a fractional CRO. Pricing benchmarks, scope templates, success criteria, and how to evaluate fractional versus a full-time chief revenue officer.",
     "summary": "Pricing, scope, and how to evaluate fractional CRO candidates against a full-time hire.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "how-to-hire-a-fractional-cmo", "title": "How to Hire a Fractional CMO: Scope, Cost, and Fit",
     "meta": "How to hire a fractional CMO. Pricing benchmarks, scope templates, success criteria, and how to decide between fractional and full-time CMO in B2B SaaS.",
     "summary": "Pricing, scope, and how to decide between fractional CMO and a full-time hire.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "how-to-hire-a-vp-of-sales", "title": "How to Hire a VP of Sales: The Founder Playbook",
     "meta": "How to hire a VP of Sales in B2B SaaS. Timing signals by ARR, scorecard, interview loop, comp targets, and the most common first-VP-Sales hiring mistakes.",
     "summary": "Timing, scorecard, interview loop, and comp for the first VP Sales hire in B2B SaaS.",
     "word_target": 1500, "date": "2026-05-15"},
    {"slug": "how-to-hire-a-head-of-revops", "title": "How to Hire a Head of RevOps: A Founder Guide",
     "meta": "How to hire a head of RevOps. Timing by ARR, scope templates, comp benchmarks from Pavilion and RepVue, scorecard, and the most common first-RevOps mistakes.",
     "summary": "Timing, scope, comp benchmarks, and scorecard for the first head of RevOps.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "how-to-build-a-pre-sales-team", "title": "How to Build a Pre-Sales Team: Hiring and Ratios",
     "meta": "How to build a pre-sales SE team in B2B SaaS. SE to AE ratios, hiring order, comp benchmarks, specialization timing, and how pre-sales scales with ACV.",
     "summary": "SE to AE ratios, hiring order, comp, and specialization timing for a pre-sales team.",
     "word_target": 1500, "date": "2026-05-15"},
    {"slug": "when-to-promote-an-sdr-to-ae", "title": "When to Promote an SDR to AE: Signals and Pitfalls",
     "meta": "When to promote an SDR to AE in B2B SaaS. Tenure benchmarks, promotion scorecard, ramp expectations, and the most common promotion mistakes inside sales teams.",
     "summary": "Tenure, scorecard, ramp expectations, and the common promotion mistakes to avoid.",
     "word_target": 1400, "date": "2026-05-15"},

    # Career path
    {"slug": "path-to-cro", "title": "The Path to CRO: Career Steps and Timing",
     "meta": "The path to CRO in B2B SaaS. Tenure benchmarks, scope progression, lateral moves, and the operating skills boards look for in a first-time CRO.",
     "summary": "Tenure, scope progression, and the skills boards look for in a first-time CRO.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "path-to-cmo", "title": "The Path to CMO: Career Steps and Timing",
     "meta": "The realistic path to CMO in B2B SaaS. Tenure benchmarks, scope progression, lateral moves, and the operating skills boards look for in a first-time CMO.",
     "summary": "Tenure, scope progression, and the skills boards look for in a first-time CMO.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "path-to-vp-revops", "title": "The Path to VP RevOps: Career Steps and Timing",
     "meta": "The realistic path to VP RevOps in B2B SaaS. Tenure benchmarks, scope progression, comp targets, and the skills CROs look for in a first-time VP RevOps.",
     "summary": "Tenure, scope progression, comp, and the skills CROs look for in a first VP RevOps.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "path-to-vp-customer-success", "title": "The Path to VP Customer Success: Career Steps",
     "meta": "The path to VP Customer Success in B2B SaaS. Tenure benchmarks, scope progression, comp, and the operating skills CROs look for in a first VP CS.",
     "summary": "Tenure, scope progression, comp, and the skills CROs look for in a first VP CS.",
     "word_target": 1400, "date": "2026-05-15"},
    {"slug": "path-from-ae-to-sales-leader", "title": "From AE to Sales Leader: A Realistic Career Path",
     "meta": "From AE to sales leader. The progression from rep to manager to director to VP, with timing benchmarks, comp ranges, and common stalls along the way.",
     "summary": "From rep to manager to director to VP. Timing, comp, and the common stalls along the way.",
     "word_target": 1400, "date": "2026-05-15"},

    # Methodology
    {"slug": "meddic-explained", "title": "MEDDIC Explained: A 2026 Sales Qualification Guide",
     "meta": "MEDDIC explained. The original framework, the MEDDPICC and MEDDICC extensions, when it works in B2B SaaS, and how teams operationalize it inside the CRM.",
     "summary": "The framework, the MEDDPICC and MEDDICC extensions, and how teams operationalize it.",
     "word_target": 1500, "date": "2026-05-15"},
    {"slug": "challenger-sale-vs-spin-selling", "title": "Challenger Sale vs SPIN Selling: A Practitioner View",
     "meta": "Challenger Sale vs SPIN Selling compared. The core mechanics of each framework, where each works in B2B sales, and how modern teams blend the two in practice.",
     "summary": "Mechanics of each framework, where each works, and how teams blend the two in practice.",
     "word_target": 1500, "date": "2026-05-15"},
    {"slug": "product-led-growth-vs-sales-led-growth", "title": "PLG vs Sales-Led Growth: A B2B SaaS Comparison",
     "meta": "Product-led growth vs sales-led growth in B2B SaaS. Unit economics, headcount math, segment fit, and how hybrid PLG plus SLG motions work in practice.",
     "summary": "Unit economics, headcount math, and how hybrid PLG plus SLG motions operate.",
     "word_target": 1500, "date": "2026-05-15"},
    {"slug": "founder-led-sales-when-to-graduate", "title": "Founder-Led Sales: When to Graduate to a Sales Team",
     "meta": "Founder-led sales: when to graduate. Signals it is time to hire sellers, the most common transition mistakes, and how to keep deal velocity through the shift.",
     "summary": "Signals to graduate from founder-led sales, common transition mistakes, and how to keep velocity.",
     "word_target": 1500, "date": "2026-05-15"},
]


# Helper to build a single guide easily — accepts the build.py-side helper
def make_guide_builder(slug, body, faqs, related):
    """Return a closure that, when called with _write_guide and GUIDES, builds the guide."""
    def builder(_write_guide, GUIDES):
        g = next(x for x in GUIDES if x["slug"] == slug)
        return _write_guide(g, body, faqs, related)
    return builder
